site_name: bazario

repo_name: chessenjoyer17/bazario
repo_url: https://github.com/chessenjoyer17/bazario

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - search.modal
    - header.autohide
    - announce.dismiss
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono
  icon:
    repo: material/github
    logo: material/book-open-variant
    admonition:
      note: octicons/tag-16
  favicon: images/favicon.ico

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home:
      - Introduction: index.md
      - Why bazario: home/whybazario.md
  - User Guide:
      - Installation: user-guide/installation.md
  - Usage:
      - Requests and handles: usage/requests_and_handlers.md
      - Notifications and handlers: usage/notifications_and_handlers.md
      - Pipeline Behaviors: usage/pipelines.md
      - Resolvers:
          - Resolvers in bazario: usage/resolvers_in_bazario.md
          - Dishka resolver: usage/dishka_resolver.md
          - Punq resolver: usage/punq_resolver.md
  - Contributing:
      - Development: contributing/development.md
      - Guidelines: contributing/guidelines.md

plugins:
  - search
  - tags

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chessenjoyer17